export const BLACK="#111111"
export const DARK_BLUE="#030F2B"
export const BLUE="#05225C"
export const LIGHT_BLUE="#1396D8"
export const LIGHTER_BLUE="#dceaff"
export const SUBTLE_BLUE="#f0f6ff"
export const DARK_GREY="#9B9B9B"
export const SEM_DARK_GREY="#dedede"
export const GREY="#D3D3D3"
export const WHITE="#efefef"
export const SUPER_WHITE="#ffffff"
export const DANGER="#880000"
export const RED="#ff0000"
export const SUCCESS="#00bc00"

